[package]
name = "getr"
version = "0.1.1"
authors = ["Julian Fondren <jfondren@minimaltype.com>"]
edition = "2018"
description = "A benchmarking wrapper around getrusage"
repository = "https://github.com/jrfondren/getr-rust"
readme = "README.md"
license = "MIT"

[dependencies]
libc = "0.2.69"
